# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 775)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/qt.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QScrollArea(MainWindow)
        self.centralwidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.centralwidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.centralwidget.setWidgetResizable(True)
        self.centralwidget.setObjectName("centralwidget")
        self.canvas = Canvas()
        self.canvas.setGeometry(QtCore.QRect(0, 0, 973, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setObjectName("canvas")
        self.centralwidget.setWidget(self.canvas)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dock_label_list = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_label_list.sizePolicy().hasHeightForWidth())
        self.dock_label_list.setSizePolicy(sizePolicy)
        self.dock_label_list.setObjectName("dock_label_list")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.listWidget_labels = QtWidgets.QListWidget(self.dockWidgetContents_4)
        self.listWidget_labels.setGeometry(QtCore.QRect(0, 0, 256, 311))
        self.listWidget_labels.setObjectName("listWidget_labels")
        self.dock_label_list.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_label_list)
        self.dock_file_list = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_file_list.sizePolicy().hasHeightForWidth())
        self.dock_file_list.setSizePolicy(sizePolicy)
        self.dock_file_list.setObjectName("dock_file_list")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.layoutWidget = QtWidgets.QWidget(self.dockWidgetContents_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 258, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_filename = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_filename.setText("")
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.verticalLayout.addWidget(self.lineEdit_filename)
        self.listWidget_files = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget_files.setObjectName("listWidget_files")
        self.verticalLayout.addWidget(self.listWidget_files)
        self.dock_file_list.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_file_list)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/svg/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNext_Image = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/svg/next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNext_Image.setIcon(icon2)
        self.actionNext_Image.setObjectName("actionNext_Image")
        self.actionPrev_Image = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/svg/previous.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPrev_Image.setIcon(icon3)
        self.actionPrev_Image.setObjectName("actionPrev_Image")
        self.actionOpen_Dir = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/svg/dir.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen_Dir.setIcon(icon4)
        self.actionOpen_Dir.setObjectName("actionOpen_Dir")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Recent.setEnabled(False)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/svg/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCreate_Polygons = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/svg/polygon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCreate_Polygons.setIcon(icon6)
        self.actionCreate_Polygons.setObjectName("actionCreate_Polygons")
        self.actionCreate_Rectangle = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/svg/square_four_angle_point.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCreate_Rectangle.setIcon(icon7)
        self.actionCreate_Rectangle.setObjectName("actionCreate_Rectangle")
        self.actionCreate_Circle = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/svg/circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCreate_Circle.setIcon(icon8)
        self.actionCreate_Circle.setObjectName("actionCreate_Circle")
        self.actionEdit_Polygon = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/svg/change.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionEdit_Polygon.setIcon(icon9)
        self.actionEdit_Polygon.setObjectName("actionEdit_Polygon")
        self.actionDelete_Polygon = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/svg/trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDelete_Polygon.setIcon(icon10)
        self.actionDelete_Polygon.setObjectName("actionDelete_Polygon")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setEnabled(False)
        self.actionUndo.setObjectName("actionUndo")
        self.actionLabel_List = QtWidgets.QAction(MainWindow)
        self.actionLabel_List.setCheckable(True)
        self.actionLabel_List.setChecked(True)
        self.actionLabel_List.setObjectName("actionLabel_List")
        self.actionFill_List = QtWidgets.QAction(MainWindow)
        self.actionFill_List.setCheckable(True)
        self.actionFill_List.setChecked(True)
        self.actionFill_List.setObjectName("actionFill_List")
        self.actionHide_Polygons = QtWidgets.QAction(MainWindow)
        self.actionHide_Polygons.setEnabled(False)
        self.actionHide_Polygons.setObjectName("actionHide_Polygons")
        self.actionView_Polygons = QtWidgets.QAction(MainWindow)
        self.actionView_Polygons.setEnabled(False)
        self.actionView_Polygons.setObjectName("actionView_Polygons")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/svg/zoom-in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_in.setIcon(icon11)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/svg/zoom-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon12)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionFit_Window = QtWidgets.QAction(MainWindow)
        self.actionFit_Window.setCheckable(True)
        self.actionFit_Window.setChecked(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/svg/zoomReset.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFit_Window.setIcon(icon13)
        self.actionFit_Window.setObjectName("actionFit_Window")
        self.actionFit_Width = QtWidgets.QAction(MainWindow)
        self.actionFit_Width.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/svg/fit-width.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFit_Width.setIcon(icon14)
        self.actionFit_Width.setObjectName("actionFit_Width")
        self.actionDuplicate_Polygon = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/svg/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDuplicate_Polygon.setIcon(icon15)
        self.actionDuplicate_Polygon.setObjectName("actionDuplicate_Polygon")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/svg/mummy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbout.setIcon(icon16)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setEnabled(False)
        self.actionRedo.setObjectName("actionRedo")
        self.actionconvert_to_dataset = QtWidgets.QAction(MainWindow)
        self.actionconvert_to_dataset.setObjectName("actionconvert_to_dataset")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Dir)
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNext_Image)
        self.menuFile.addAction(self.actionPrev_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCreate_Polygons)
        self.menuEdit.addAction(self.actionCreate_Rectangle)
        self.menuEdit.addAction(self.actionCreate_Circle)
        self.menuEdit.addAction(self.actionDuplicate_Polygon)
        self.menuEdit.addAction(self.actionEdit_Polygon)
        self.menuEdit.addAction(self.actionDelete_Polygon)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuView.addAction(self.actionLabel_List)
        self.menuView.addAction(self.actionFill_List)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionHide_Polygons)
        self.menuView.addAction(self.actionView_Polygons)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoom_in)
        self.menuView.addAction(self.actionZoom_out)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFit_Window)
        self.menuView.addAction(self.actionFit_Width)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionconvert_to_dataset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionOpen_Dir)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreate_Polygons)
        self.toolBar.addAction(self.actionCreate_Rectangle)
        self.toolBar.addAction(self.actionCreate_Circle)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEdit_Polygon)
        self.toolBar.addAction(self.actionDuplicate_Polygon)
        self.toolBar.addAction(self.actionDelete_Polygon)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrev_Image)
        self.toolBar.addAction(self.actionNext_Image)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionZoom_out)
        self.toolBar.addAction(self.actionFit_Window)
        self.toolBar.addAction(self.actionFit_Width)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Label-it"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Tools"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dock_label_list.setWindowTitle(_translate("MainWindow", "Labels"))
        self.dock_file_list.setWindowTitle(_translate("MainWindow", "File List"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionNext_Image.setText(_translate("MainWindow", "&Next Image"))
        self.actionNext_Image.setShortcut(_translate("MainWindow", "D"))
        self.actionPrev_Image.setText(_translate("MainWindow", "&Prev Image"))
        self.actionPrev_Image.setShortcut(_translate("MainWindow", "A"))
        self.actionOpen_Dir.setText(_translate("MainWindow", "Open Dir"))
        self.actionOpen_Dir.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionOpen_Recent.setText(_translate("MainWindow", "Open Recent"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save As"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionClose.setText(_translate("MainWindow", "&Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+F4"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionCreate_Polygons.setText(_translate("MainWindow", "Create Polygons"))
        self.actionCreate_Polygons.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionCreate_Rectangle.setText(_translate("MainWindow", "Create Rectangle"))
        self.actionCreate_Rectangle.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionCreate_Circle.setText(_translate("MainWindow", "Create Circle"))
        self.actionEdit_Polygon.setText(_translate("MainWindow", "Edit Polygon"))
        self.actionEdit_Polygon.setToolTip(_translate("MainWindow", "Edit Polygon"))
        self.actionDelete_Polygon.setText(_translate("MainWindow", "Delete Polygon"))
        self.actionUndo.setText(_translate("MainWindow", "&Undo"))
        self.actionLabel_List.setText(_translate("MainWindow", "Label List"))
        self.actionFill_List.setText(_translate("MainWindow", "Fill List"))
        self.actionHide_Polygons.setText(_translate("MainWindow", "Hide Polygons"))
        self.actionView_Polygons.setText(_translate("MainWindow", "Show Polygons"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoom_in.setShortcut(_translate("MainWindow", "=, +"))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out"))
        self.actionZoom_out.setShortcut(_translate("MainWindow", "-, _"))
        self.actionFit_Window.setText(_translate("MainWindow", "Fit Window"))
        self.actionFit_Window.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionFit_Width.setText(_translate("MainWindow", "Fit Width"))
        self.actionFit_Width.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.actionDuplicate_Polygon.setText(_translate("MainWindow", "Duplicate Polygon"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionconvert_to_dataset.setText(_translate("MainWindow", "convert to dataset"))
        self.actionconvert_to_dataset.setToolTip(_translate("MainWindow", "convert to dataset"))
from canvas import Canvas
import img_rc
